#pragma once

#define PLAYER_BASE_LEVEL 1
#define PLAYER_BASE_EXP 0
#define PLAYER_BASE_EXP 10
#define PLAYER_BASE_HEALTH 100
#define PLAYER_BASE_ATTACK 5

#define PLAYER_NEXT_LEVEL_EXP_EXPONENT 0.3
#define PLAYER_HEALTH_EXPONENT 0.4
#define PLAYER_ATTACK_EXPONENT 0.5

#define ENEMY_HEALTH_EXPONENT 0.4
#define ENEMY_ATTACK_EXPONENT 0.4
