#pragma once
#define WINDOW_WIDTH 1024
#define WINDOW_HEIGHT 768
#define TITLE_FONT_SIZE 36
#define BUTTON_FONT_SIZE 24
#define ADDITIONAL_FRAMERATE 3
#define MAX_FRAMERATE 120
#define GUI_BREAK_TIME 50 // milliseconds

// for debugging
#define DEPTH_START 0
#define ROCKS_START 0

#define MINER_FRAMES_CNT 10
#define MINER_BACKGROUNDS_CNT 5
#define EXPLOSION_FRAMES_CNT 16

#define DIG_SPEED_START 1
#define DIG_SPEED_COST_BASE 10
#define DIG_SPEED_COST_EXPONENT 3
#define DIG_SPEED_INCREMENT_VAL 5

#define DIG_CLICK_START 5
#define DIG_CLICK_MULTIPLIER_COST_BASE 1
#define DIG_CLICK_MULTIPLIER_COST_EXPONENT 4
#define DIG_CLICK_MULTIPLIER_VAL 2

#define ROCK_DEPTH_RATIO 2
#define DEPTH_LAYER_BASE 10

#define DYNAMITE_POWER_START 1000
#define DYNAMITE_POWER_COST_BASE 10000
#define DYNAMITE_POWER_COST_EXPONENT 4
#define DYNAMITE_POWER_MULTIPLIER_VAL 1.5

#define DYNAMITE_COST_BASE 1000
#define DYNAMITE_COST_EXPONENT 2
