#pragma once
#define WINDOW_WIDTH 1024
#define WINDOW_HEIGHT 768
#define TITLE_FONT_SIZE 36

#define MINER_FRAMES_CNT 10
#define MINER_BACKGROUNDS_CNT 5

#define DIG_SPEED_START 1
#define DIG_SPEED_COST_BASE 10
#define DIG_SPEED_COST_EXPONENT 0.2
#define DIG_SPEED_BASE 1
#define DIG_SPEED_EXPONENT 0.6

#define DIG_CLICK_START 5
#define DIG_CLICK_MULTIPLIER_COST_BASE 1
#define DIG_CLICK_MULTIPLIER_COST_EXPONENT 0.4
#define DIG_CLICK_MULTIPLIER_VAL 2

#define ROCK_DEPTH_RATIO 5
